### ISSUE TITLE
スレッドエラー

### ISSUE THREAD

**Issue by k-ogaswr** [MaxfieldWalker/SpinnerMeijin#3]
スピナーを変更してからメイン画面に戻ると、メイン画面でスピナーを回転させることができない（落ちはしない）。
rotateメソッドが実行されていないことが原因だと思われるが、rotateメソッドを追加実行すると、
”Only the original thread that created a view hierarchy can touch its views.”というエラーが発生。
スレッド関連の処理を調べる必要があるかも　
スピナーを回転させながらショップに行くと落ちるのもスレッドが原因かも　by小笠原＆藤原

**Comment by maxfie1d** [comment]
まあスレッド周りはOSによって結構制約あったりするから、みんな揃った時に解決しましょう！
報告ありがとう

**Comment by maxfie1d** [comment]
Fixed with d698cb6.
